### ISSUE TITLE
XcodeGen導入

### ISSUE THREAD

**Issue by kagaffy** [YoshikiTsukada/AppStore#1]
```
name: AppStore
targets:
  AppStore:
    type: application
    platform: iOS
    sources:
      - path: AppStore
```
